alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: richardbonett.com
  type: PRIMARY
  zone: richardbonett.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: rbonettcom
    match:
      path:
        prefix: /
  - component:
      name: twosday
    match:
      path:
        prefix: /twosday
name: rbonettcom
region: nyc
static_sites:
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/rbonett/rbonettcom.git
  name: rbonettcom
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/rbonett/rbonettcom.git
  index_document: twosday.html
  name: twosday
  source_dir: pages
