alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: rbonettcom
    match:
      authority:
        exact: ""
      path:
        prefix: /
  - component:
      name: twosday
    match:
      authority:
        exact: ""
      path:
        prefix: /twosday
name: rbonettcom
region: nyc
static_sites:
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/rbonett/rbonettcom.git
  name: rbonettcom
- environment_slug: html
  git:
    branch: main
    repo_clone_url: https://github.com/rbonett/rbonettcom.git
  index_document: pages/twosday
  name: twosday
